**Python Sudoku Solver - Computerphile**
https://youtu.be/G_UYXzGuqvM

Professor Thorsten Altenkirch on a recursive Sudoku solver. 

In [0]:
# example grid as in the vdo
# since we are only allowed to fill numbers 1-9
# therefore, we fill in the black cells with 0

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]


In [0]:
import numpy as np

In [4]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [0]:
def possible(y,x,n):
  global grid
  # n is the number we want to fill in

  # 1st 
  # check if n already existed in vertical (y) axis
  # if exists, return False (not possible)
  for i in range(9):
    if grid[y][i] == n:
      return False

  # 2nd
  # check horizontal (x) axis
  for i in range(9):
    if grid[i][x] == n:
      return False

  # 3rd
  # check the 3x3 local grid
  x0 = (x//3)*3 
  y0 = (y//3)*3
  for i in range(3):
    for j in range(3):
      if grid[y0+i][x0+j] == n:
         return False

  # return true if pass all 3 checks.
  return True

In [6]:
# try n = 3
possible(4,4,3)

False

In [7]:
# try n = 5
possible(4,4,5)

True

In [0]:
def solve():
  global grid
  for y in range(9):
    for x in range(9):
      # Find blank positions in the grid (value = 0)
      if grid[y][x] == 0:
        # Loop n from 1-9
        for n in range(1,10):
          if possible(y,x,n):
            grid[y][x] = n
            solve()

            # This is where backtracking happens
            # Reset the latest position back to 0 and try with new n value
            grid[y][x] = 0
        return
  print(np.matrix(grid))
  input('More?')

In [9]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More?


In [0]:
# modify the grid values
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,0,0]]

In [11]:
solve()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More?
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More?
